import accessPointSetup
from os import path
import sys
from BashUtility import BashHelper
from shutil import move, copy

SCRIPT_DIR = path.dirname(__file__)

CONFIG_FILE_NAME = "dhcpd.conf"

def TestStripAllCommentsFromScript(logger, fileName):
    filePath = path.join(SCRIPT_DIR, fileName) 
    if(path.isfile(filePath+'.bk')):
        copy(filePath+'.bk',filePath)
    BashHelper.StripAllCommentsFromScript(filePath)
    BashHelper.StripBlankLineFromScript(filePath)
def TestEditDhcpConfig(logger, fileName):
    filePath = path.join(SCRIPT_DIR, fileName) 
    if(path.isfile(filePath+'.bk')):
        copy(filePath+'.bk',filePath)
    BashHelper.StripAllCommentsFromScript(filePath)
    BashHelper.StripBlankLineFromScript(filePath)
    accessPointSetup.EditDhcpConfig(logger,filePath,path.join(SCRIPT_DIR,'dhcpd.conf.template'))

def TestEditIscDhcpServerConfig(logger, fileName):
    filePath = path.join(SCRIPT_DIR, fileName) 
    if(path.isfile(filePath+'.bk')):
        copy(filePath+'.bk',filePath)
    accessPointSetup.EditIscDhcpServerConfig(logger,filePath)
    BashHelper.StripAllCommentsFromScript(filePath)
    BashHelper.StripBlankLineFromScript(filePath)
def TestEditInterfacesConfig(logger, fileName):
    filePath = path.join(SCRIPT_DIR, fileName) 
    if(path.isfile(filePath+'.bk')):
        copy(filePath+'.bk',filePath)
    accessPointSetup.EditInterfacesConfig(logger,filePath)
    BashHelper.StripAllCommentsFromScript(filePath)
    BashHelper.StripBlankLineFromScript(filePath)
def TestEditHostApdConfig(logger, fileName):
    filePath = path.join(SCRIPT_DIR, fileName) 
    if(path.isfile(filePath+'.bk')):
        copy(filePath+'.bk',filePath)
    accessPointSetup.EditHostApdConfig(logger,filePath)
    BashHelper.StripAllCommentsFromScript(filePath)
    BashHelper.StripBlankLineFromScript(filePath)
def TestEditHostApdDefault(logger, fileName):
    filePath = path.join(SCRIPT_DIR, fileName) 
    if(path.isfile(filePath+'.bk')):
        copy(filePath+'.bk',filePath)
    accessPointSetup.EditHostApdDefault(logger,filePath)
    BashHelper.StripAllCommentsFromScript(filePath)
    BashHelper.StripBlankLineFromScript(filePath)
def TestEditSysctlConfig(logger, fileName):
    filePath = path.join(SCRIPT_DIR, fileName) 
    if(path.isfile(filePath+'.bk')):
        copy(filePath+'.bk',filePath)
    accessPointSetup.EditSysctlConfig(logger,filePath)
    BashHelper.StripAllCommentsFromScript(filePath)
    BashHelper.StripBlankLineFromScript(filePath)
def TestEditIp4_forward(logger, fileName):
    iptableOutput ="""
# Generated by iptables-save v1.4.21 on Sun Aug 14 19:53:17 2016
*filter
:INPUT ACCEPT [1:40]
:FORWARD ACCEPT [0:0]
:OUTPUT ACCEPT [0:0]
-A FORWARD -i eth0 -o wlan0 -m state --state RELATED,ESTABLISHED -j ACCEPT
-A FORWARD -i wlan0 -o eth0 -j ACCEPT
-A FORWARD -i wlan1 -o wlan0 -m state --state RELATED,ESTABLISHED -j ACCEPT
-A FORWARD -i wlan0 -o wlan1 -j ACCEPT
COMMIT
# Completed on Sun Aug 14 19:53:17 2016
# Generated by iptables-save v1.4.21 on Sun Aug 14 19:53:17 2016
*nat
:PREROUTING ACCEPT [0:0]
:INPUT ACCEPT [0:0]
:OUTPUT ACCEPT [0:0]
:POSTROUTING ACCEPT [0:0]
-A POSTROUTING -o eth0 -j MASQUERADE
-A POSTROUTING -o wlan1 -j MASQUERADE
COMMIT
# Completed on Sun Aug 14 19:53:17 2016

"""
    accessPointSetup.EditIp4_forward(logger,iptableOutput,path.join(SCRIPT_DIR,fileName))
 

if __name__ == "__main__":
    logger = BashHelper.SetupLogger('testWifiAPConfig',"./testWifiAPConfig.log")
    TestEditDhcpConfig(logger, "dhcpd.conf")
#    TestStripAllCommentsFromScript(logger,"dhcpd.conf")
#    TestEditIscDhcpServerConfig(logger, "isc-dhcp-server")
#    TestEditInterfacesConfig(logger, "interfaces")
#    TestEditHostApdConfig(logger, "hostapd.conf")
#    TestEditHostApdDefault(logger, "hostapd")
#    TestEditSysctlConfig(logger, "sysctl.conf")
    TestEditIp4_forward(logger,"testTestEditIp4_forward")